# Generated by Django 4.0.3 on 2024-01-11 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_cart_order', to='product.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shopping_cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_shopping_cart', to='product.shoppingcart'),
        ),
    ]
